version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: muthu@1997
      POSTGRES_DB: green_trace_local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
